image: python:3.9

stages: 
  - test
  - deploy

.all:
  allow_failure: false 

# encode: base64 -w0 priv_key > priv_key_base64.txt
# decode: cat priv_key_base64.txt | base64 -di

# https://docs.gitlab.com/ee/ci/ssh_keys/
before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY_ENCODED64" | base64 -di | tr -d '\r' | ssh-add -  
  # - ssh -o StrictHostKeyChecking=no -vvv kdm@213.135.55.88
  - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
  - ssh-keyscan -H 213.135.55.88 >> ~/.ssh/known_hosts
  - |- 
    if [[ "x$(ssh -q kdm@213.135.55.88 exit)$?" == "x0" ]] ; then 
      echo "ssh test: connection ok"
    else 
      echo "ssh test: something went wrong..." 
    fi
  - pwd 
  - ls -latr
  - pip install -r requirements.txt
  - pip freeze
  - git submodule update --init --recursive --remote

test-pages:
  stage: test
  extends: .all
  artifacts:
    untracked: true
    paths:
        - 'tmp'
    expire_in: 1 week
    when: always # on_failure
  script:
    - mkdocs build --verbose --clean --strict --site-dir tmp
    - ssh kdm@213.135.55.88 'rm -rf /home/kdm/html'
    - scp -r tmp/ kdm@213.135.55.88:/home/kdm/html/ 


# For GitLab Pages, the job must have a specific name, called pages. This setting tells the runner you want the job to deploy your website.
# Due to some problems with custom domain in gitlab, we host the webpage from out machine: 213.135.55.88
# pages: 
#   stage: deploy
#   only:
#     - master
#   needs: [test-pages]
#   dependencies:
#     - test-pages
#   extends: .all
#   script:
#     - mkdocs build --verbose --clean --strict --site-dir public
#   artifacts:
#     paths:
#       - public


