stages: 
  - test
  - deploy

.all:
  tags: 
    - www
  allow_failure: false 
  # when: always
  # only:
  #     - tags
  #     - triggers
  #     - schedules
  #     - web
  variables:
    ENV_NAME: "mkdocs-env"

# test-script:
#   stage: test
#   extends: .all
#   script:
#     - echo "a"
#     - source .gitlab-ci/sample_script.sh && echo "ok"
#     - echo $teraz
#     - echo "b"
#     - .gitlab-ci/prepare_venv.sh
#     - echo "c"

test-pages:
  stage: test
  extends: .all
  artifacts:
    untracked: true
    paths:
        - 'tmp'
    expire_in: 1 week
    when: always #on_failure
  script:
    - source .gitlab-ci/prepare_venv.sh && echo "env prepared"
    - mkdocs build --verbose --clean --strict

publish-pages:
  stage: deploy
  needs: [test-pages]  # TODO: it shall start only when test-pages stage is successful
  dependencies:
    - test-pages
  extends: .all
  script:
    - source .gitlab-ci/prepare_venv.sh
    - mkdocs gh-deploy
    
