stages: 
  - test
  - deploy

.all:
  tags: 
    - www
  allow_failure: false 
  # when: always
  # only:
  #     - tags
  #     - triggers
  #     - schedules
  #     - web
  variables:
    ENV_NAME: "mkdocs-env"
    GIT_STRATEGY: none
    CLONE_DIR: "temp-docs-repo-dir"
    # script:

before_script:
  - pwd 
  - eval $(ssh-agent -s)
  - ls -la /home/gitlab-runner-nginx/.ssh
  - ssh-add -l && echo ok
  - ssh-add /home/gitlab-runner-nginx/.ssh/appbot-2-hpc-docs_v2 <<< $'75375'&
  - ssh-add -l && echo ok
  - ls -la
  - rm -rf $CLONE_DIR
  - git clone git@git.icm.edu.pl:owu/hpc-docs.git $CLONE_DIR
  - cd $CLONE_DIR
  - pwd 
  - ls -la
  - ssh -vT git@git.icm.edu.pl


test-pages:
  stage: test
  extends: .all
  artifacts:
    untracked: true
    paths:
        - 'tmp'
    expire_in: 1 week
    when: always #on_failure
  script:
    - source .gitlab-ci/prepare_venv.sh && echo "env prepared"
    - mkdocs build --verbose --clean --strict

publish-pages:
  stage: deploy
  needs: [test-pages]
  dependencies:
    - test-pages
  extends: .all
  script:
    - source .gitlab-ci/prepare_venv.sh && echo "env prepared"
    - mkdocs gh-deploy
