image: python:3.9

stages: 
  - test
  - deploy

.all:
  allow_failure: false 

before_script:
  - pip install -r requirements
  - git submodule update --init --recursive --remote

test-pages:
  stage: test
  extends: .all
  artifacts:
    untracked: true
    paths:
        - 'tmp'
    expire_in: 1 week
    when: always # on_failure
  script:
    - mkdocs build --verbose --clean --strict --site-dir tmp

publish-pages:
  stage: deploy
  only:
    - master
  needs: [test-pages]
  dependencies:
    - test-pages
  extends: .all
  script:
    - mkdocs build --verbose --clean --strict --site-dir public

  artifacts:
    paths:
      - public
