stages: 
  - test
  - deploy

.all:
  tags: 
    - www
  allow_failure: false 
  when: always
  dependencies: []    
  variables:
    ENV_NAME: "mkdocs-env"

        
test-pages:
  extends: .all
  artifacts:
    untracked: true
    paths:
        - 'tmp'
    expire_in: 1 week
    when: always #on_failure
  script:
    - bash .gitlab-ci/prepare_venv.sh && echo "env prepared"
    - mkdocs build --verbose --clean --strict
  allow_failure: false 

publish-pages:
  stage: deploy
  extends: .all
  script:
    - bash .gitlab-ci/prepare_venv.sh
    - mkdocs gh-deploy
  allow_failure: false 
