stages: 
  - test
  - deploy

test-pages:
  stage: deploy
  tags: 
    - www
  when: always
  script:
    .gitlab-ci/prepare_venv.sh
    mkdocs build --verbose --clean --strict
  allow_failure: false 

publish-pages:
  stage: deploy
  tags: 
    - www
  when: always
  script:
    .gitlab-ci/prepare_venv.sh
    mkdocs gh-deploy
  allow_failure: false 
