stages: 
  - test
  - deploy

test-pages:
  stage: test
  tags: 
    - www
  when: always
  variables: 
    ENV_NAME: "mkdocs-env"
  script:
    # .gitlab-ci/prepare_venv.sh
    # workon $ENV_NAME
    export VIRTUALENVWRAPPER_PYTHON=/bin/python3
    export VIRTUALENVWRAPPER_VIRTUALENV=/home/gitlab-runner-nginx/.local/bin/virtualenv
    source ~/.local/bin/virtualenvwrapper.sh
    workon mkdocs-env
    mkdocs build --verbose --clean --strict
  allow_failure: false 

publish-pages:
  stage: deploy
  tags: 
    - www
  when: always
  variables: 
    ENV_NAME: "mkdocs-env"
  script:
    .gitlab-ci/prepare_venv.sh
    workon $ENV_NAME
    mkdocs gh-deploy
  allow_failure: false 
