stages: 
  - test
  - deploy

.all:
  tags: 
    - www
  allow_failure: false 
  # when: always
  # only:
  #     - tags
  #     - triggers
  #     - schedules
  #     - web
  variables:
    ENV_NAME: "mkdocs-env"
    GIT_STRATEGY: none



    # script:


# test-script:
#   stage: test
#   extends: .all
#   script:
#     - echo "a"
#     - source .gitlab-ci/sample_script.sh && echo "ok"
#     - echo $teraz
#     - echo "b"
#     - .gitlab-ci/prepare_venv.sh
#     - echo "c"

test-pages:
  stage: test
  extends: .all
  artifacts:
    untracked: true
    paths:
        - 'tmp'
    expire_in: 1 week
    when: always #on_failure
  script:
    - source .gitlab-ci/before_script.sh
    - source .gitlab-ci/prepare_venv.sh && echo "env prepared"
    - mkdocs build --verbose --clean --strict

publish-pages:
  stage: deploy
  needs: [test-pages]  # TODO: it shall start only when test-pages stage is successful
  dependencies:
    - test-pages
  extends: .all
  script:
    - source .gitlab-ci/prepare_venv.sh
    - git remote set-url origin git@git.icm.edu.pl:owu/hpc-docs.git
    - eval $(ssh-agent -s)
    - ls -la /home/gitlab-runner-nginx/.ssh
    - ssh-add -l && echo ok
    - ssh-add /home/gitlab-runner-nginx/.ssh/appbot-2-hpc-docs_v2 <<< $'75375'&
    - ssh-add -l && echo ok
    - git branch -v
    - git remote -v
    - ssh-add -l
    - ssh-add -L
    - eval `ssh-agent -s`
    - ssh-add -l
    - ls -la /home/gitlab-runner-nginx/.ssh
    - ssh -vT git@git.icm.edu.pl
    - mkdocs gh-deploy





    # - BUILD_DIR=$HOME/builds/$RUNNER_TOKEN/0
    # - CLONE_DIR="$BUILD_DIR/$CI_PROJECT_PATH"
    # - cd $BUILD_DIR
    # - pwd 
    # - rm -rf $CLONE_DIR
    # - mkdir -p $CLONE_DIR
    # - eval $(ssh-agent -s)
    # - ls -la /home/gitlab-runner-nginx/.ssh
    # - ssh-add -l && echo ok
    # - ssh-add /home/gitlab-runner-nginx/.ssh/appbot-2-hpc-docs_v2 <<< $'75375'&
    # - ssh-add -l && echo ok
    # - pwd 
    # - ls -la
    # - git clone git@git.icm.edu.pl:owu/hpc-docs.git $CLONE_DIR
    # - cd $CLONE_DIR
    # - pwd 
    # - ls -la