stages: 
  - test
  - deploy

test-pages:
  stage: deploy
  tags: 
    - www
  when: always
  variables: 
    ENV_NAME: "mkdocs-env"
  script:
    .gitlab-ci/prepare_venv.sh
    workon $ENV_NAME
    mkdocs build --verbose --clean --strict
  allow_failure: false 

publish-pages:
  stage: deploy
  tags: 
    - www
  when: always
  variables: 
    ENV_NAME: "mkdocs-env"
  script:
    .gitlab-ci/prepare_venv.sh
    workon $ENV_NAME
    mkdocs gh-deploy
  allow_failure: false 
