image: python:3.9

stages: 
  - test
  - deploy

.all:
  allow_failure: false 

before_script:
  - pwd 
  - ls -latr
  - pip install -r requirements.txt
  - pip freeze
  - git submodule update --init --recursive --remote

test-pages:
  stage: test
  extends: .all
  artifacts:
    untracked: true
    paths:
        - 'tmp'
    expire_in: 1 week
    when: always # on_failure
  script:
    - mkdocs build --verbose --clean --strict --site-dir tmp

pages: # For GitLab Pages, the job must have a specific name, called pages. This setting tells the runner you want the job to deploy your website.
  stage: deploy
  only:
    - master
  needs: [test-pages]
  dependencies:
    - test-pages
  extends: .all
  script:
    - mkdocs build --verbose --clean --strict --site-dir public
  artifacts:
    paths:
      - public
