site_name: Dokumentacja ICM UW
site_description: Komputery Dużej Mocy w ICM UW
site_author: ICM
site_url: https://icm.edu.pl/

repo_name: ICM-HPC
repo_url: https://git.icm.edu.pl/owu/hpc-docs
edit_uri: https://git.icm.edu.pl/owu/hpc-docs/edit/master/docs/

extra:
  homepage: https://icm.edu.pl/

theme: 
  logo: 'images/Logo_icm_biale.png'
  name: 'material'
  custom_dir: overrides
  palette:
    primary: 'blue-grey'
    accent: 'green'
  features:
    - search.highlight

plugins:
  - search # necessary for search to work
  - i18n:
      languages:
          pl: "PL"
          en: "EN"
      default_language: 'pl'
      no_translation:
        pl: "Ta strona nie jest tłumaczona na polski."
        en: "This page is not translated to English."
      translate_nav:
        pl:
          section_instrukcje: "Instrukcje"
          sub_section_logowanie: "Logowanie"
          page_nazwa_konta_i_haslo: "Nazwa użytkownika i hasło"
          page_logowanie_SSH: "Logowanie SSH"
          page_logowanie_SSH_windows: "Logowanie SSH (Użytkownicy Windows)"
          page_SSH_tunel: "Tunelowanie SSH"
          section_system_alokacji_zasobow: "System alokacji zasobów"
          page_wstep_i_definicje: "Wstęp i Definicje"
          page_zakladanie_konta:  "Zakładanie konta"
          page_rodzaje_alokacji: "Rodzaje alokacji"
          page_rozliczanie_projektu: "Rozliczanie projektu"
          page_faq_system_alokacji_zasobow: "FAQ"
          page_poczta_elektroniczna: "Poczta elektroniczna"
          page_NEC_podstawy_uzycia: "NEC - podstawy użycia"
          page_SOL_sieci_neuronowe: "SOL - sieci neuronowe"
          page_regulamin_uzytkownika_icm: "Regulamin użytkownika"
        en:
          section_instrukcje: "Tutorials"
          sub_section_logowanie: "Login"
          page_nazwa_konta_i_haslo: "User name and password"
          page_logowanie_SSH: "Login via SSH"
          page_logowanie_SSH_windows: "Login via SSH (Windows)"
          page_SSH_tunel: "SSH tunneling"
          section_system_alokacji_zasobow: "Resource Allocation System"
          page_wstep_i_definicje: "Introduction and definitions"
          page_zakladanie_konta:  "Creating account"
          page_rodzaje_alokacji: "Types of allocations"
          page_rozliczanie_projektu: "Reports and publications"
          page_faq_system_alokacji_zasobow: "FAQ"
          page_poczta_elektroniczna: "ICM e-mail"
          page_NEC_podstawy_uzycia: "NEC - basic usage"
          page_SOL_sieci_neuronowe: "SOL - neural networks"
          page_regulamin_uzytkownika_icm: "Terms of Service"
  - mkdocs-jupyter:
      include_source: True # true - render on web; false - download
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - monorepo

# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
    - attr_list
    - fenced_code
    - codehilite
    - mdx_math
    - admonition
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_css:
  - style.css

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# list of emoji: https://gist.github.com/rxaviers/7360908

nav:
- Strona główna: index.md
- Formalności:
    - Kto może być użytkownikiem: O_zasobach_ICM/Formalnosci/uzytkownik.md
    - Warunki korzystania: O_zasobach_ICM/Formalnosci/warunki.md
    - page_regulamin_uzytkownika_icm: O_zasobach_ICM/Formalnosci/regulamin.pl.md
    - page_regulamin_uzytkownika_icm: O_zasobach_ICM/Formalnosci/regulamin.en.md
    - Polityka prywatności: O_zasobach_ICM/Formalnosci/polityka_prywatnosci.md
- Zasoby sprzętowe:
    - Komputery: O_zasobach_ICM/Zasoby/komputery_w_icm.md
    - Przechowywanie danych: O_zasobach_ICM/Zasoby/przechowywanie_danych.md
- Aplikacje:
    - Dostępne oprogramowanie: O_zasobach_ICM/Aplikacje/aplikacje.md
    - Dostępne kompilatory: O_zasobach_ICM/Aplikacje/kompilatory.md
    - CI status: O_zasobach_ICM/Aplikacje/ci_status.md
- Licencje krajowe:
    - ANSYS: Licencje_krajowe/ansys.md
    - Gaussian: Licencje_krajowe/gaussian.md
- section_system_alokacji_zasobow:
    - page_wstep_i_definicje: System_alokacji_zasobow/wstep_i_definicje.pl.md
    - page_wstep_i_definicje: System_alokacji_zasobow/wstep_i_definicje.en.md
    - page_zakladanie_konta: System_alokacji_zasobow/zakladanie_konta.pl.md
    - page_zakladanie_konta: System_alokacji_zasobow/zakladanie_konta.en.md
    - page_rodzaje_alokacji: System_alokacji_zasobow/rodzaje_alokacji.pl.md
    - page_rodzaje_alokacji: System_alokacji_zasobow/rodzaje_alokacji.en.md
    - page_rozliczanie_projektu: System_alokacji_zasobow/rozliczanie_projektu.pl.md
    - page_rozliczanie_projektu: System_alokacji_zasobow/rozliczanie_projektu.en.md
    - page_faq_system_alokacji_zasobow: System_alokacji_zasobow/faq.pl.md
    - page_faq_system_alokacji_zasobow: System_alokacji_zasobow/faq.en.md
    - page_poczta_elektroniczna: System_alokacji_zasobow/poczta_elektroniczna.pl.md
    - page_poczta_elektroniczna: System_alokacji_zasobow/poczta_elektroniczna.en.md
- section_instrukcje:
  - sub_section_logowanie:
    - page_nazwa_konta_i_haslo: Tutorials/Logowanie/nazwa_konta_i_haslo.pl.md
    - page_nazwa_konta_i_haslo: Tutorials/Logowanie/nazwa_konta_i_haslo.en.md
    - page_logowanie_SSH: Tutorials/Logowanie/ssh.pl.md
    - page_logowanie_SSH: Tutorials/Logowanie/ssh.en.md 
    - page_logowanie_SSH_windows: Tutorials/Logowanie/ssh_windows.pl.md
    - page_logowanie_SSH_windows: Tutorials/Logowanie/ssh_windows.en.md
    - page_SSH_tunel: Tutorials/Logowanie/ssh_tunel.pl.md
    - page_SSH_tunel: Tutorials/Logowanie/ssh_tunel.en.md
  - Podstawy HPC:
    - Wstęp: Tutorials/HPC-intro/introduction.md
    - Bash i terminal: Tutorials/HPC-intro/bash_intro.md
    - Kopiowanie plików: Tutorials/HPC-intro/kopiowanie_plikow.md
    - Zlecanie zadań do SLURM: Tutorials/HPC-intro/slurm_intro.md
    - Ustawianie środowiska: Tutorials/HPC-intro/ustawianie_srodowiska.md
    - Instalacja nowego oprogramowania: Tutorials/HPC-intro/instalacja_oprogramowania.md
    - Instalacja oprogramowania - spack: Tutorials/HPC-intro/instalacja_oprogramowania_spack.md
    - Terminal multiplexer: Tutorials/HPC-intro/terminal_multiplexer.md
    - Status zadania: Tutorials/HPC-intro/status_zadania.md
    - Status grantu/konta/qos: Tutorials/HPC-intro/status_grantu_i_konta.md
  - Podstawy GPU:
    - Introduction (Cheat Sheet): Tutorials/GPU-intro/introduction.en.md
    - Hello World: Tutorials/GPU-intro/hello_world.en.md
    - Vector Add: Tutorials/GPU-intro/vector_add.en.md
    - Element-wise Matrix Add: Tutorials/GPU-intro/matrix_addition.en.md
    - Parallel reduction: Tutorials/GPU-intro/parallel_reduction.en.md
    - Thrust library: Tutorials/GPU-intro/thrust.en.md
  - Kontenery:
    - Singularity: Tutorials/Kontenery/singularity_intro.md
  - NEC SX-Aurora Tsubasa:
    - page_NEC_podstawy_uzycia: Tutorials/NEC/nec_podstawy.pl.md
    - page_NEC_podstawy_uzycia: Tutorials/NEC/nec_podstawy.en.md
    - page_SOL_sieci_neuronowe: Tutorials/NEC/sol.en.md
    - page_SOL_sieci_neuronowe: Tutorials/NEC/sol.pl.md
  - Środowisko wirtualne:
    - Python: Tutorials/python/python.md
    - Anaconda: Tutorials/python/anaconda.md
- Szkolenia:
  - Informacje: Szkolenia/informacje.md
  - Materiały:
    - Wprowadzenie do obliczeń na komputerach ICM 2021: Szkolenia/intro_icm_2021.md
    - Wprowadzenie do obliczeń na komputerach ICM 2019: Szkolenia/intro_icm_2019.md
    - Wprowadzenie do obliczeń wektorowych – NEC SX-Aurora Tsubasa: Szkolenia/intro_nec.md
    - Effective Neural Networks Without GPU (SOL): Szkolenia/intro_sol.md
    - Sesja Q&A: Szkolenia/sesja_qa.md
    # - Obliczenia grafowe i sieciowe: Szkolenia/intro_grafy.md
    - Obliczenia grafowe i sieciowe: '!include docs/Szkolenia/grafy/mkdocs.yml'
  - Archiwum: Szkolenia/archiwum.md
- Sesje użytkowników KDM:
  - Aktualności: Sesje_KDM/aktualnosci.md
  - Sesja 2021: 
    - Informacje: Sesje_KDM/sesja2021/sesja2021.md
    - Prelegenci: Sesje_KDM/sesja2021/prelegenci.md
  - Archiwum: Sesje_KDM/archiwum.md

- Kontakt: kontakt.md
