site_name: KDM @ ICM UW
site_description: Komputery Dużej Mocy @ ICM UW
site_author: ICM
#strict: true

theme:
  logo: 'images/Logo_icm_czarne.svg'
  name: 'material'
  palette:
    primary: 'white'
    accent: 'light blue'

repo_name: ICM-HPC
repo_url: https://github.com/ICM-UW/hpc-docs
edit_uri: "https://github.com/ICM-UW/hpc-docs/edit/master/docs/"

markdown_extensions:
    - fenced_code
    - codehilite
    - mdx_math
    - admonition
    - footnotes
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
- Komputery Dużej Mocy @ ICM UW: index.md

- O zasobach ICM:
  - Formalności:
    - Kto może być użytkownikiem: O_zasobach_ICM/Formalnosci/uzytkownik.md
    - Warunki korzystania: O_zasobach_ICM/Formalnosci/warunki.md
    - Regulamin użytkownika: O_zasobach_ICM/Formalnosci/regulamin.md
  - Zasoby:
    - Komputery: O_zasobach_ICM/Zasoby/komputery_w_icm.md
    - Przechowywanie danych: O_zasobach_ICM/Zasoby/przechowywanie_danych.md
  - Aplikacje:
    - Aplikacje: O_zasobach_ICM/Aplikacje/aplikacje.md
    - CI status: O_zasobach_ICM/Aplikacje/ci_status.md
- Podręcznik grantowy:
    - Zakładanie konta: Podrecznik_grantowy/Zakładanie_konta.md
    - Jak wystąpić o grant obliczeniowy: Podrecznik_grantowy/Jak_wystąpić_o_grant_obliczeniowy.md
    - Przyznawane zasoby: Podrecznik_grantowy/Przyznawane_zasoby.md
    - Kierownik oraz współwykonawcy grantu: Podrecznik_grantowy/Kierownik_oraz_nowi_współwykonawcy_grantu.md
    - Sprawozdania i publikacje w grancie: Podrecznik_grantowy/Sprawozdania_i_publikacje_w_grancie.md
    - Rozliczanie grantu: Podrecznik_grantowy/Rozliczanie_grantu.md
    - Zamykanie grantu: Podrecznik_grantowy/
    - Użytkownik i kilka grantów obliczeniowych: Podrecznik_grantowy/Użytkownik_i_kilka_grantów_obliczeniowych.md
#- Najczęściej zadawane pytania:
- Tutorials:
  - Podstawy HPC:
    - Wstęp: Tutorials/HPC-intro/introduction.md
    - Case - BASH i terminal: Tutorials/HPC-intro/bash_intro.md
    - Case - Logowanie SSH: Tutorials/HPC-intro/ssh_intro.md
    - Case - Logowanie SSH (Użytkownicy Windows): Tutorials/HPC-intro/ssh_windows.md
    - Case - Kopiowanie plików: Tutorials/HPC-intro/kopiowanie_plikow.md
    - Case - Zlecanie zadań do SLURM: Tutorials/HPC-intro/slurm_intro.md
    - Case - Ustawianie środowiska: Tutorials/HPC-intro/module.md
    - Case - Status zadania: Tutorials/HPC-intro/status_zadania.md
    - Case - Status grantu/konta/qos: Tutorials/HPC-intro/status_grantu_i_konta.md
  - Podstawy GPU:
    - Introduction (Cheat Sheet): Tutorials/GPU-intro/introduction.md
    - Hello World: Tutorials/GPU-intro/hello_world.md
    - Vector Add: Tutorials/GPU-intro/vector_add.md
    - Element-wise Matrix Add: Tutorials/GPU-intro/matrix_addition.md
    - Parallel reduction: Tutorials/GPU-intro/parallel_reduction.md
  - NEC SX-Aurora Tsubasa:
    - Basic usage: Tutorials/NEC/basic_usage.md
    - SOL - Neural Networks: Tutorials/NEC/sol.md
  - Python - środowisko wirtualne: Tutorials/python.md

- Szkolenia:
  - Informacje: Szkolenia/informacje.md
  - Materiały:
    - Wprowadzenie do obliczeń na komputerach ICM: Szkolenia/intro_icm.md
    - Wprowadzenie do obliczeń wektorowych – NEC SX-Aurora Tsubasa: Szkolenia/intro_nec.md
  - Archiwum: Szkolenia/archiwum.md
    
- Kontakt: kontakt.md
