site_name: ICM HPC tutorials
site_description: The reference tutorials for HPC @ ICM UW.
site_author: ICM
#strict: true

theme:
  logo: 'images/Logo_icm_czarne.svg'
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'

repo_name: ICM-HPC
repo_url: https://github.com/ICM-UW/hpc-docs
edit_uri: "https://github.com/ICM-UW/hpc-docs/edit/master/docs/"

markdown_extensions:
    - fenced_code
    - codehilite
    - mdx_math
    - admonition
    - footnotes
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
- Welcome to ICM HPC tutorials: index.md

- O zasobach ICM:
  - Superkomputery: O_zasobach_ICM/0_superkomputery.md
  - Kto może być użytkownikiem: O_zasobach_ICM/1_uzytkownik.md
  - Warunki korzystania: O_zasobach_ICM/2_warunki.md
  - Regulamin użytkownika: O_zasobach_ICM/3_regulamin.md
  - Jaki komputer wybrać: O_zasobach_ICM/4_jaki_komputer.md
  - Aplikacje: O_zasobach_ICM/5_aplikacje.md
  
- Podstawy HPC:
  - Wstęp: HPC-intro/0_Introduction.md
  - Bash – Podstawy: HPC-intro/1_BashIntro.md
  - Logowanie SSH – Podstawy: HPC-intro/2_sshIntro.md
  - Logowanie SSH – Użytkownicy Windows: HPC-intro/3_ssh_windows.md
  - SLURM – Podstawy: HPC-intro/4_SlurmIntro.md
  - Komputery w ICM: HPC-intro/5_Komputery_w_ICM.md
  
- Podstawy GPU:
  - Introduction (Cheat Sheet): GPU-intro/0_Introduction.md
  - Hello World: GPU-intro/1_HelloWorld.md
  - Vector Add: GPU-intro/2_VectorAdd.md
  - Element-wise Matrix Add: GPU-intro/3_MatrixAddition.md
  - Parallel reduction: GPU-intro/4_ParallelReduction.md

- NEC SX-Aurora Tsubasa:
  - Introduction: NEC-SX-Aurora-Tsubasa/0_introduction.md
  - Basic usage: NEC-SX-Aurora-Tsubasa/1_basic_usage.md
  - "SOL: Neural Networks": NEC-SX-Aurora-Tsubasa/2_sol.md

- Szkolenia:
  - Informacje: Szkolenia/informacje.md
  - Materiały:
    - Wprowadzenie do obliczeń na komputerach ICM: Szkolenia/intro_icm.md
    - Wprowadzenie do obliczeń wektorowych – NEC SX-Aurora Tsubasa: Szkolenia/intro_nec.md
  - Archiwum: Szkolenia/archiwum.md
    