site_name: ICM HPC tutorials
site_description: The reference tutorials for HPC @ ICM UW.
site_author: ICM
#strict: true

theme:
  logo: 'images/Logo_icm_czarne.svg'
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'

repo_name: ICM-HPC
repo_url: https://github.com/ICM-UW/hpc-docs
edit_uri: "https://github.com/ICM-UW/hpc-docs/edit/master/docs/"

markdown_extensions:
    - fenced_code
    - codehilite
    - mdx_math
    - admonition
    - footnotes
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
- Welcome to ICM HPC tutorials: index.md

- O zasobach ICM:
  - Formalności:
    - Superkomputery: O_zasobach_ICM/Formalnosci/superkomputery.md
    - Kto może być użytkownikiem: O_zasobach_ICM/Formalnosci/uzytkownik.md
    - Warunki korzystania: O_zasobach_ICM/Formalnosci/warunki.md
    - Regulamin użytkownika: O_zasobach_ICM/Formalnosci/regulamin.md
    - Jaki komputer wybrać: O_zasobach_ICM/Formalnosci/jaki_komputer.md
  - Komputery:
    - Komputery w ICM: O_zasobach_ICM/Komputery/komputery_w_icm.md
    - QOS: O_zasobach_ICM/Komputery/qos.md
    - Przechowywanie danych: O_zasobach_ICM/Komputery/przechowywanie_danych.md
  - Aplikacje:
    - Aplikacje: O_zasobach_ICM/Aplikacje/aplikacje.md
    - CI status: O_zasobach_ICM/Aplikacje/ci_status.md

- Podstawy HPC:
  - Wstęp: HPC-intro/introduction.md
  - Case - BASH i terminal: HPC-intro/bash_intro.md
  - Case - Logowanie SSH: HPC-intro/ssh_intro.md
  - Case - Logowanie SSH (Użytkownicy Windows): HPC-intro/ssh_windows.md
  - Case - Kopiowanie plików: HPC-intro/kopiowanie_plikow.md
  - Case - Zlecanie zadań do SLURM: HPC-intro/slurm_intro.md
  - Case - Ustawianie środowiska: HPC-intro/module.md
  - Case - Status grantu/konta: HPC-intro/status_grantu_i_konta.md

- Podstawy GPU:
  - Introduction (Cheat Sheet): GPU-intro/introduction.md
  - Hello World: GPU-intro/hello_world.md
  - Vector Add: GPU-intro/vector_add.md
  - Element-wise Matrix Add: GPU-intro/matrix_addition.md
  - Parallel reduction: GPU-intro/parallel_reduction.md

- NEC SX-Aurora Tsubasa:
  - Introduction: NEC-SX-Aurora-Tsubasa/introduction.md
  - Basic usage: NEC-SX-Aurora-Tsubasa/basic_usage.md
  - SOL - Neural Networks: NEC-SX-Aurora-Tsubasa/sol.md

- Szkolenia:
  - Informacje: Szkolenia/informacje.md
  - Materiały:
    - Wprowadzenie do obliczeń na komputerach ICM: Szkolenia/intro_icm.md
    - Wprowadzenie do obliczeń wektorowych – NEC SX-Aurora Tsubasa: Szkolenia/intro_nec.md
  - Archiwum: Szkolenia/archiwum.md
    
- Kontakt: kontakt.md