site_name: ICM HPC tutorials
site_description: The reference tutorials for HPC @ ICM UW.
site_author: ICM
#strict: true

theme:
  logo: 'images/Logo_icm_czarne.svg'
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'

repo_name: ICM-HPC
repo_url: https://github.com/ICM-UW/hpc-docs
edit_uri: "https://github.com/ICM-UW/hpc-docs/edit/master/docs/"

markdown_extensions:
    - fenced_code
    - codehilite
    - mdx_math
    - admonition
    - footnotes
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
- About HPC @ ICM UW: index.md

- O zasobach ICM:
  - Formalności:
    - Kto może być użytkownikiem: O_zasobach_ICM/Formalnosci/uzytkownik.md
    - Warunki korzystania: O_zasobach_ICM/Formalnosci/warunki.md
    - Regulamin użytkownika: O_zasobach_ICM/Formalnosci/regulamin.md
  - Zasoby:
    - Komputery: O_zasobach_ICM/Zasoby/komputery_w_icm.md
    - Przechowywanie danych: O_zasobach_ICM/Zasoby/przechowywanie_danych.md
  - Aplikacje:
    - Aplikacje: O_zasobach_ICM/Aplikacje/aplikacje.md
    - CI status: O_zasobach_ICM/Aplikacje/ci_status.md
- Podręcznik grantowy:
    - Zakładanie konta:
    - Jak wystąpić o grant obliczeniowy:
    - Przyznawane zasoby:
    - Kierownik oraz współwykonawcy grantu:
    - Sprawozdania i publikacje w grancie:
    - Rozliczanie grantu:
    - Zamykanie grantu:
    - Użytkownik i kilka grantów obliczeniowych:
- Najczęściej zadawane pytania:
- Tutorials:
  - Podstawy HPC:
    - Wstęp: Tutorials/HPC-intro/introduction.md
    - Case - BASH i terminal: Tutorials/HPC-intro/bash_intro.md
    - Case - Logowanie SSH: Tutorials/HPC-intro/ssh_intro.md
    - Case - Logowanie SSH (Użytkownicy Windows): Tutorials/HPC-intro/ssh_windows.md
    - Case - Kopiowanie plików: Tutorials/HPC-intro/kopiowanie_plikow.md
    - Case - Zlecanie zadań do SLURM: Tutorials/HPC-intro/slurm_intro.md
    - Case - Ustawianie środowiska: Tutorials/HPC-intro/module.md
    - Case - Status zadania: Tutorials/HPC-intro/status_zadania.md
    - Case - Status grantu/konta/qos: Tutorials/HPC-intro/status_grantu_i_konta.md
  - Podstawy GPU:
    - Introduction (Cheat Sheet): Tutorials/GPU-intro/introduction.md
    - Hello World: Tutorials/GPU-intro/hello_world.md
    - Vector Add: Tutorials/GPU-intro/vector_add.md
    - Element-wise Matrix Add: Tutorials/GPU-intro/matrix_addition.md
    - Parallel reduction: Tutorials/GPU-intro/parallel_reduction.md
  - NEC SX-Aurora Tsubasa:
    - Basic usage: Tutorials/NEC/basic_usage.md
    - SOL - Neural Networks: Tutorials/NEC/sol.md
  - Python - środowisko wirtualne: Tutorials/python.md

- Szkolenia:
  - Informacje: Szkolenia/informacje.md
  - Materiały:
    - Wprowadzenie do obliczeń na komputerach ICM: Szkolenia/intro_icm.md
    - Wprowadzenie do obliczeń wektorowych – NEC SX-Aurora Tsubasa: Szkolenia/intro_nec.md
  - Archiwum: Szkolenia/archiwum.md
    
- Kontakt: kontakt.md
